### ISSUE TITLE
Appendix B?

### ISSUE THREAD

**Issue by jondolan** [lyndyaxon/RECONSO-CONOPS#3]
Should we take the table (work in progress) from Command Execution Test Procedure Appendix A that describes (some) of the telemetry value nominal ranges and add it to this document?

**Comment by lyndyaxon** [comment]
That's probably a good idea... i can start working on that... it's a pain in the ass to make tables in LaTeX

**Comment by jondolan** [comment]
Appendix A now has the nominal telemetry ranges tables.
